### ISSUE TITLE
Media Keys

### ISSUE THREAD

**Issue by WladyX** [SokoloffA/radiola#1]
Hey, 
Your app si almost perfect, all it lacks is media keys support, is this something you are thinking of implementing?
Thank you very much for sharing this app!

**Comment by SokoloffA** [comment]
Hi! I didn't expect anyone to use the program, I made it for myself.
I am glad that the program turned out to be useful for you. 

I will add support for multimedia keys

**Comment by WladyX** [comment]
Wow, such a fast response, thank you!
Maybe add a donate button to the project? Would like to buy you a beer!

**Comment by SokoloffA** [comment]
Many thanks! I added the button.

**Comment by SokoloffA** [comment]
I made a new release with support for multimedia keys.

**Comment by WladyX** [comment]
Wow, works great! Thank you!
