### ISSUE TITLE
Feature Request: Previous/Next Favorite with Media Keys

### ISSUE THREAD

**Issue by cheeseslope** [SokoloffA/radiola#10]
One of my favorite Radiola features is that utilizes the Play/Pause media key. 

I switch radio stations pretty regularly, and I’d appreciate if pressing the Next/Previous media keys would move to the next station in my Radiola favorites list. This is how the SomaFM iOS app works, and I’d love to have the same functionality on my Mac.

**Comment by SokoloffA** [comment]
I will add this to the next release. It will be turned off by default, but you can turn it on in the settings.

**Comment by cheeseslope** [comment]
Really appreciate this new feature — thank you!
