### ISSUE TITLE
Features Request: iCloud sync and flag for information

### ISSUE THREAD

**Issue by Mesandro** [SokoloffA/radiola#12]
Hello, congrats for this super software. Simple, fast functional. As soon as I found out it replaced all other solutions! Using it on multiple machines a synchronization of the cloud favorites would be useful, while I found the small floating window showing information about the radio particularly annoying (at least in my use). It would be nice to be able to turn off the information with a setting. For the rest it's perfect for me. Thank you!

**Comment by SokoloffA** [comment]
Thanks for the kind words!

> Using it on multiple machines a synchronization of the cloud favorites would be useful

I was thinking about synchronization, there are some technical problems. But I will try to solve them.

---------
> I found the small floating window showing information about the radio particularly annoying

You mean the tooltip?
![Снимок экрана 2023-07-01 в 11 46 19](https://github.com/SokoloffA/radiola/assets/854935/19556826-dfc7-40be-9d06-95ff162cfb2d)

I thought it wouldn't be annoying since it only shows up when you hover the mouse. In any case, I can make a setting for that. 


P.S.
I would be happy if you would write one idea per issue. Then I can close the issues I've done.

**Comment by Mesandro** [comment]
> I was thinking about synchronization, there are some technical problems. But I will try to solve them.

It's not a big problem, currently I solved it by simply copying the bookmarks file present in the "Application Support" folder and copying it to the other machine. Also a bookmark import/export function I think would be useful in the same way as the cloud.


> You mean the tooltip?

Exactly. During my work I use many apps in the menu bar and many times that annoys me "visually" not at a functional level obviously as it is very convenient


> P.S.
> I would be happy if you would write one idea per issue. Then I can close the issues I've done.

Excuse me! It was my first comment on github, I signed up specifically for your software ;)

**Comment by SokoloffA** [comment]
> Excuse me! It was my first comment on github, I signed up specifically for your software ;)

No problem.

Satisfy my curiosity, how did you know about the program?

**Comment by Mesandro** [comment]
> > Excuse me! It was my first comment on github, I signed up specifically for your software ;)
> 
> No problem.
> 
> Satisfy my curiosity, how did you know about the program?

I used to use similar software called "Radio" which hasn't been updated in years now, but it still worked on the Ventura. I discovered your software via Reddit in a post discussing similar alternatives :)
