### ISSUE TITLE
Feature Request: Channel List Import

### ISSUE THREAD

**Issue by matthiassturm** [SokoloffA/radiola#13]
To make adding your favourite channels just a drag n drop job, it would be nice to have the ability to import the full list from Radio Browser.

https://www.radio-browser.info/

**Comment by SokoloffA** [comment]
Sorry for the long reply!
I'll see how it can be done.

**Comment by SokoloffA** [comment]
I looked at their API. Task doesn't look very complicated. 

I see it as dialog with searching by tags and genres, plus test listening.
What would you like to see also?

**Comment by matthiassturm** [comment]
Search by country would be really interesting too.

**Comment by SokoloffA** [comment]
I've [released a beta version](https://github.com/SokoloffA/radiola/releases/tag/v5.99.1) of the software with fulfil your dreams. 
I'm interested to hear your opinion.

**Comment by matthiassturm** [comment]
Yeah that's looking very good. Thanks a lot!

What could be improved:
- "by country" be a multiple choice dropdown
- "by tag" could also possibly be a multiple choice dropdown?
- country flag as an icon infront of the station name
- make initial search field more prominent or initial load of the full list without the need to use the search (better UX)
- the *by tag/by country/by name* could be integrated into the search area - may be a better arrangement

**Comment by SokoloffA** [comment]
Done in the 6.0 release
