### ISSUE TITLE
How to use the Feature "Group Radiostations"?

### ISSUE THREAD

**Issue by Karlheinz-B** [SokoloffA/radiola#14]
Dear Alexander,

thank you for this great program.
I recently updated it and saw, that there's an option to group stations.
How does this work? I couldn't figure this out, drag & drop doesn't seem to work also in combination with CMD or Shift and also no buttons.

Thank you very much.

Also import & export of stations (Feature Request exists already) would be great as during updating all my previous used stations were gone (:

Best Regards,

Karl

**Comment by SokoloffA** [comment]
On the station window in the main menu, click **File->New Station Group**. After that drag and drop the stations into the created group.

**Comment by SokoloffA** [comment]
I hope my clarification was helpful to you.

**Comment by denilsonsa** [comment]
> On the station window in the main menu, click File->New Station Group. 

Would be nice to add a "New Group" button to the toolbar. We already have a `+` and a `-` button in there. Adding a button for new group would be the next logical thing. It would also help with the usability/discoverability of that feature, as I too spent a couple of minutes until I explored the application menu.
