### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by Ranxeon** [SokoloffA/radiola#15]
Not really an issue but something that's been bothering me for a while.

Love the app and everything that's been done so far. Not a fan of the app icon though so I made one that looks a bit nicer in the dock. Nothing fancy, but maybe others find it useful too.

PNG & ICNS provided. Either Preview/Copy/Get Info/Paste or replace the icon in Package Contents/Resources.

<img width="543" alt="radiola_dock" src="https://github.com/SokoloffA/radiola/assets/142297619/d96ee9ad-2ca5-4af1-8b59-e0789f4b8af7">

[radiola_icon.zip](https://github.com/SokoloffA/radiola/files/12356602/radiola_icon.zip)

*** Feel free to delete this post if inappropriate in any way ***

**Comment by st1ng7ay** [comment]
maybe better to have an option to hide dock icon ?

**Comment by SokoloffA** [comment]
I apologize for the long silence, I've been having some problems in my life.

@Ranxeon 
I like your icons. Now I'm preparing a new big upgrade with support for i[nternet services](13). I will include your icons in it.

@st1ng7ay 
I will add this option.

**Comment by SokoloffA** [comment]
@Ranxeon Do you have the SVG version?

**Comment by Ranxeon** [comment]
Sure, here you go.

[radiola.svg.zip](https://github.com/SokoloffA/radiola/files/13169750/radiola.svg.zip)
