### ISSUE TITLE
bitrate

### ISSUE THREAD

**Issue by faitno** [SokoloffA/radiola#16]
How show bitrate of station? and another information about audio stream - 44/96Hz, codec mp3/flac/aac
Nice program! I love this small and functional player!

**Comment by SokoloffA** [comment]
Now I'm working on a new big upgrade with support for i[nternet services](13). Such information will definitely be useful there.

I think, to keep the interface clean, it's possible to display such information for "local" stations by a separate button (and hotkey).

**Comment by SokoloffA** [comment]
Done in the 6.0 release
