### ISSUE TITLE
Feature Request: Favourite Songs

### ISSUE THREAD

**Issue by Ranxeon** [SokoloffA/radiola#17]
Would it be possible to add a favourite function so that whenever a song you really like is playing and you want to find it later or explore the artist more, you can "heart it"?

It could be something as simple as saving the song and artist name permanently in a txt file, but one can go crazy and give it a visual representation much like the history feature.

The important part in the end is that one can come back and find the songs that were saved.

![heart](https://github.com/SokoloffA/radiola/assets/142297619/266a4a93-16aa-4975-b0c9-8719f910bd01)

**Comment by SokoloffA** [comment]
The easiest thing I see is to tag songs in the history, and add the "Favorite" filter to the history window.

I'll do it, but a little later. Now I'm working on a new big upgrade with support for [internet services](13). I don't want to delay it any further.

**Comment by Ranxeon** [comment]
Ì understand and no pressure :)
I think I speak for everyone when I say that your work here is very much appreciated.

**Comment by SokoloffA** [comment]
I added this to the [beta version of Radiola 6.99.1](https://github.com/SokoloffA/radiola/releases/tag/v6.99.1).
If you are interested, you can test it by downloading [Radiola-6.99.1.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.1/Radiola-6.99.1.dmg)

**Comment by SokoloffA** [comment]
I have released the second beta, if you are interested you can download it [at the link](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by SokoloffA** [comment]
In release 7.0.0
