### ISSUE TITLE
Awesome player thanks!

### ISSUE THREAD

**Issue by Wiredframe** [SokoloffA/radiola#2]
Thanks very much for this great little app. Works great. Was looking for a macOS Alternative for TrayRadio / GaGa Player.

**Comment by SokoloffA** [comment]
Thanks!

**Comment by SokoloffA** [comment]
Hello! You have expressed interest in my program, thanks! Now I have released a new version. It supports the following features:
* Improved (I hope) appearance and look of the main window.
* A song history window.
* Automatic updates.
