### ISSUE TITLE
Searching for stations doesn't work (5.99.1)

### ISSUE THREAD

**Issue by pagaille** [SokoloffA/radiola#22]
Lists are empty in the Radio browser

When searching, I can see this in stdout : 

```
** ERROR ******************************
* The operation couldn’t be completed. (Radiola.RadioBrowser.Error error 0.)
* On: Radiola.RadioBrowserStationsByName
*******************************************
```

Txs

**Comment by SokoloffA** [comment]
I fixed this in the new release. 

Unfortunately, I have some problems in my life and I don't have time for pet projects. So I released the new version as is.

But I hope to return to the development and support of the project soon.

**Comment by pagaille** [comment]
Thanks ! I wish you the best.
