### ISSUE TITLE
Some streams metadata show as json

### ISSUE THREAD

**Issue by kolokolovg** [SokoloffA/radiola#23]
Отпишу по русски.
На одном из стримов который я слушаю (https://sevfm.ru:9006/stream)
Метаданные не парсятся а отображаются в заголовке целиком как json.

**Comment by kolokolovg** [comment]
<img width="565" alt="image" src="https://github.com/SokoloffA/radiola/assets/21097728/8b9390c3-d069-4abb-bc7b-301500dbbe90">

**Comment by SokoloffA** [comment]
Добрый день!
С метаданными проблема, кто во что горазд, кто передает _ARTIST - TITLE_ кто _TITLE - ARTIST_, кто в JSON-ах, я встречал в XML. Причем и JSON и XML каждый раз самодельные. 
Я искал, может есть стандарт, но пока не нашел, похоже нет стандарта на формат метаданных. Я думаю как разрулить эту проблему, может придется писать эмпирический разборщик, но страшно не хочется. Это заранее проигранная битва, в любом случае будут ложные срабатывания.   

Если знаете опенсорсную программу, которая корректно показывает метаданные, я буду счастлив подсмотреть ее код.

**Comment by kolokolovg** [comment]
> Если знаете опенсорсную программу, которая корректно показывает метаданные, я буду счастлив подсмотреть ее код.

Почему то мне кажется что метаданные генерятся по разному разными стриминговыми серверами.
У ссылки которую я дал - генератор потока icecast.
Возможно если попробовать воспроизвести на другом потоке с таким же серверным ПО то ошибка воспроизведется.
Ну и тогда тут действительно нужна какая то библиотека которая разбирает метаданные от различных источников.

**Comment by SokoloffA** [comment]
Unfortunately, I have some problems in my life and I don't have time for pet projects. So I released the new version as is.

But I hope to return to the development and support of the project soon.

**Comment by SokoloffA** [comment]
Оставлю это здесь для себя, возможно поможет в дальнейшем.

* http://wiki.shoutcast.com/wiki/SHOUTcast_XML_Metadata_Specification

**Comment by SokoloffA** [comment]
I have released the second beta, if you are interested you can download it [at the link](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by kolokolovg** [comment]
<img width="456" alt="Снимок экрана 2024-06-06 в 06 48 28" src="https://github.com/SokoloffA/radiola/assets/21097728/96231294-da06-4372-9c57-49ff6b36a093">
confirmed.
