### ISSUE TITLE
Support Email And Iphone Version

### ISSUE THREAD

**Issue by marcelo4768** [SokoloffA/radiola#24]
Thanks for the application, the best is simple, minimalist. There is no way to send comments to the developer (email support in the app settings). An iPhone version would be incredible.

**Comment by SokoloffA** [comment]
I will definitely add information about this issue-tracker to the about dialog.

It is unlikely to expect an iPhone version, at least in the near future. In recent months, I have absolutely no time to takes care of my projects.

**Comment by SokoloffA** [comment]
Done in the 6.1.0 release
