### ISSUE TITLE
pretty neat, but where can I find the URLs for these radio stations?

### ISSUE THREAD

**Issue by RedemptionC** [SokoloffA/radiola#25]
Hi, I'm interested in BBC or VOA, but I'm kinda a noob to network radios

**Comment by SokoloffA** [comment]
There are several ways:

* The easiest way is to use the feature that appeared in yesterday's release - search in the "Radio browser" catalog.
* Sometimes websites post a link to listen in an external player. Unfortunately, this has been done less and less recently.
* Use the search, search the Internet for something like "bbc listen stream" or "bbc listen m3u". There are many directories on the Internet that keep lists of streams.

**Comment by RedemptionC** [comment]
@SokoloffA ahh, the browser feature is great, but is it buggy or something?
I mean, the typed keyword isn't shown
![image](https://github.com/SokoloffA/radiola/assets/17563754/c9ec22fb-a077-49ec-85fc-7f374171a6b5)

**Comment by RedemptionC** [comment]
also, once you found an interesting radio station using the browser, it seems that you can't add it to "my stations" by right clicking it or something?

**Comment by SokoloffA** [comment]
> the browser feature is great, but is it buggy or something?
> I mean, the typed keyword isn't shown

This is definitely my bug with the width constraint.
Right now, make the window wider and you will see the text.

> also, once you found an interesting radio station using the browser, it seems that you can't add it to "my stations" by right clicking it or something?

You can add a station using the indicator button.
![Снимок экрана 2024-03-10 в 14 05 44](https://github.com/SokoloffA/radiola/assets/854935/481c6680-fcec-44c3-85b4-c4f1f97ab5d3)

**Comment by SokoloffA** [comment]
I fixed the width restriction. I'll wait a bit, maybe other minor bugs will be found, then I'll fix them too. In any case, I will release an update in a few days.

**Comment by RedemptionC** [comment]
@SokoloffA ahh I just noticed the icon. I mean, will it be more intuitive if it's a plus sign or something?

**Comment by SokoloffA** [comment]
The icon also acts as an indicator, so the plus sign will be unclear.
Perhaps I will add a drop-down menu in future versions of the program.

**Comment by SokoloffA** [comment]
Done in the 6.1.0 release
