### ISSUE TITLE
Can't change device for playing

### ISSUE THREAD

**Issue by paulmory** [SokoloffA/radiola#27]
**Relevant for 6.0.x**
Only system default device is available for playing when you've been changed device in settings.

**Comment by SokoloffA** [comment]
Are additional devices displayed in the system volume control popup?

I'll write a small debugging program and ask you to gather more information.

**Comment by SokoloffA** [comment]
Was there a problem in previous versions of the program?

**Comment by SokoloffA** [comment]
Thanks for the kick. It looks like I've found a problem, an idiotic typo.
https://github.com/SokoloffA/radiola/blob/28a1a9619955ef8a9ae13f53e22f844bc29166ba/Radiola/Player.swift#L78

Today, when I get to the computer, I'll fix and check it.

**Comment by SokoloffA** [comment]
@paulmory 
Oh, I won't notice your PR. 
**Special and huge thanks for the PR!**

**Comment by SokoloffA** [comment]
Done in the 6.1.0 release
