### ISSUE TITLE
Network usage while paused

### ISSUE THREAD

**Issue by jon-daemon** [SokoloffA/radiola#29]
When I pause a stream I notice that the app is still downloading some data. Is this normal behavior?

![Screenshot 2024-03-12 at 14 57 09](https://github.com/SokoloffA/radiola/assets/206048/3a6c947a-ceec-479f-b16a-76429a999d82)

![Screenshot 2024-03-12 at 15 59 24](https://github.com/SokoloffA/radiola/assets/206048/7a8f53b8-cb3b-433a-b23f-e80a3cefc9c5)

**Comment by SokoloffA** [comment]
It's weird for me. The program does not transmit any telemetry or other information. I'm too lazy for this :)

There are only 3 parts of the program where traffic can be generated:

1. The actual music playback. You say that the music is not playing at this moment.
2. Requests to www.radio-browser.info . Several DNS and HTTP requests are made there, but only when you are explicitly looking for stations.
3. Updates. The program uses the Sparkle library to support updates and check for new updates. If auto-update is enabled, the program periodically downloads the file https://sokoloffa.github.io/radiola/feed.xml

I think, this is most likely the last point.
I'll do some research on this. How long did the program download 15 MB?

**Comment by SokoloffA** [comment]
I was wrong. These are not updates, the AVPlayer class continues to download data in a paused state. 
I changed the code, now the download is interrupted after a pause.

**Comment by SokoloffA** [comment]
Done in the 6.1.0 release
