### ISSUE TITLE
Can you please add an option to set a global hotkey to open the main window?

### ISSUE THREAD

**Issue by hyperphysin** [SokoloffA/radiola#30]
It's quite cumbersome to click the menu bar icon.

**Comment by SokoloffA** [comment]
Звучит разумно. Я посмотрю как это можно сделать.

**Comment by SokoloffA** [comment]
I added this to the [beta version of Radiola 6.99.1](https://github.com/SokoloffA/radiola/releases/tag/v6.99.1).
If you are interested, you can test it by downloading [Radiola-6.99.1.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.1/Radiola-6.99.1.dmg)

**Comment by SokoloffA** [comment]
I have released the second beta, if you are interested you can download it [at the link](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by hyperphysin** [comment]
It works great. 👍

**Comment by SokoloffA** [comment]
In release 7.0.0
