### ISSUE TITLE
play/pause with spacebar when the main window is active

### ISSUE THREAD

**Issue by hyperphysin** [SokoloffA/radiola#31]
Can you please make spacebar to play/pause like other music apps?

**Comment by SokoloffA** [comment]
I added this to the [beta version of Radiola 6.99.1](https://github.com/SokoloffA/radiola/releases/tag/v6.99.1).
If you are interested, you can test it by downloading [Radiola-6.99.1.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.1/Radiola-6.99.1.dmg)

**Comment by SokoloffA** [comment]
I have released the second beta, if you are interested you can download it [at the link](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by SokoloffA** [comment]
In release 7.0.0
