### ISSUE TITLE
Blurred start/pause button inside the player

### ISSUE THREAD

**Issue by kostazzz** [SokoloffA/radiola#32]
Hi, please replace the play/pause button with a vector icon in .svg or .pdf format, it is now blurred. I attached a screenshot.
<img width="156" alt="scr 2024-04-08 в 13 57 52" src="https://github.com/SokoloffA/radiola/assets/20332897/df984d8b-3390-4e81-aac5-5c87a91e8906">

**Comment by SokoloffA** [comment]
Sorry, I was sure I changed the icon to the standard system icon. I will do that in the near future.

**Comment by SokoloffA** [comment]
I added this to the [beta version of Radiola 6.99.1](https://github.com/SokoloffA/radiola/releases/tag/v6.99.1).
If you are interested, you can test it by downloading [Radiola-6.99.1.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.1/Radiola-6.99.1.dmg)

**Comment by kostazzz** [comment]
На БигСур запустилось в меню бае, но иконка не активная. 
Ни чего не происходит, закрывать пришлось через Монитор Активности.

Спасибо

**Comment by SokoloffA** [comment]
Подтверждаю, смог воспроизвести на Monterey. И даже нашел коммит который сломал, осталось найти где я накосячил.

**Comment by SokoloffA** [comment]
Вроде починил, у на Monterey запускается. Сделал [вторую бету](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by SokoloffA** [comment]
Спасибо за помощь!

**Comment by kolokolovg** [comment]
Основная иконка перестала быть прозрачной по этому ишью?
Можно вернуть снова прозрачную иконку без белой подложки? Хотя бы для сономовской сборки?
Или так нельзя - для разных версий оси разные иконки?

**Comment by kostazzz** [comment]
Александр, спасибо.

Могу ещё посоветовать косметические исправления.

1. Лучше убрать обводку у (+ -) сейчас в середине обводка дублитуется. 
2. Sidebar (station/ tag...) дать возможность сжимать на усмотрение пользователей, сейчас слушком много пустого пространства остаёться.
3. Прошлая версия требует 13 mb ram, новая 33 mb.
 
Проблема: первый раз запустил из открытого .dmg, после запустил старую версию и после этого переместил новую в папку Приложение, и рога не смогла запустить радио станцию, хотя до этого всё ок было.



Спасибо.

**Comment by kostazzz** [comment]
Отправил случайно не законченое письмо. 

Да, старые иконки не потдерживают прозрачность.

**Comment by kostazzz** [comment]
>  
> Проблема: первый раз запустил из открытого .dmg, после запустил старую версию и после этого переместил новую в папку Приложение, и рога не смогла запустить радио станцию, хотя до этого всё ок было.

Проблем исчезла и ram стало около 15 мб. 
Проблемы нету, только первые 2 пункта.

**Comment by kostazzz** [comment]
Ошибка: после 15 мин прослушивания отключилось 2 раза, не понятно почему. 
Ещё пришлю потверждение и сравню с прошлой версией.

Иконка в меню баре: верхвние дуги слишком близко прилипают к иконке треугольника. 
Прикрепил пример как лучше.

**Comment by kostazzz** [comment]
Если сложно, могу поправить иконку. Даром. :)

**Comment by kostazzz** [comment]
Потверждаю, произвольно отключаеться каждые 15-20 мин.

**Comment by kostazzz** [comment]
Возможно проблема с отключением у меня, прошлая версия тоже стала отключаться.

**Comment by kolokolovg** [comment]
насчет памяти я не смотрел сколько релизная версия потребляла
по 2 бетке - скриншот
но лично я не вижу проблем в количестве потребляемой озу

<img width="696" alt="Снимок экрана 2024-06-06 в 08 25 16" src="https://github.com/SokoloffA/radiola/assets/21097728/cf191949-00b7-4f1f-afa9-cdf1626af49e">

**Comment by SokoloffA** [comment]
Ух сколько всего, и разом! Давайте я попробую структурировать чтоб не забыть чего. 

## 1. Основная иконка
>Основная иконка перестала быть прозрачной по этому ишью?

Если речь про иконку приложения, 
![Screenshot_20240606_105031](https://github.com/SokoloffA/radiola/assets/854935/8e734f87-a638-4756-9598-b0124f672607)
то она сознательно была изменена по issue #15. Старая иконка сливалась с фоном, особенно с голубым. 
Мне не совсем нравится новая, несколько выделяется она. Я попробую немного уменьшить квадрат, и добавить немного прозрачности к нему, или сделать его серее. 

Способа иметь несколько иконок в приложении я не знаю.

## 2. Обводка у (+ -) 
> Лучше убрать обводку у (+ -) сейчас в середине обводка дублитуется.

Когда я безуспешно пытался переписать программу на SwiftUI, то у меня нарисовался другой концепт для этих кнопок:
https://github.com/SokoloffA/radiola/assets/854935/397e51de-48a6-4e7f-b042-e51b819920dd
Как вам?

## 3. Ширина Sidebar
> Sidebar (station/ tag...) дать возможность сжимать на усмотрение пользователей, сейчас слушком много пустого пространства остаёться.

Я не помню почему я задал такой большой минимум для ширины. Я сделаю поменьше. Это самое простое. 

## 4. Потребление памяти.
У меня при старте потребляет 10М, после начала воспроизведения 25М. Я думаю на современных машинах это норм, главное чтоб не текло. 

## 5. Верхние дуги слишком близко прилипают к иконке треугольника.
> Иконка в меню баре: верхвние дуги слишком близко прилипают к иконке треугольника.
Прикрепил пример как лучше. 

Примера я не увидел ни в почте, ни на github. Но это не важно, я понял о чем ты. Я сделаю треугольник чуть меньше, возьму предыдущий кадр анимации.


_Ничего я не пропустил?_

**Comment by kostazzz** [comment]
Александр, ещё мелочи от меня. :)

> 2024-06-06, в 11:39, Alexander Sokolov ***@***.***> написал(а):
> 
> 
> Ух сколько всего, и разом! Давайте я попробую структурировать чтоб не забыть чего.
> 
> 1. Основная иконка
> 
> Основная иконка перестала быть прозрачной по этому ишью?
> 
> Если речь про иконку приложения,
> Screenshot_20240606_105031.png (view on web) <https://github.com/SokoloffA/radiola/assets/854935/8e734f87-a638-4756-9598-b0124f672607>
> то она сознательно была изменена по issue #15 <https://github.com/SokoloffA/radiola/issues/15>. Старая иконка сливалась с фоном, особенно с голубым.
> Мне не совсем нравится новая, несколько выделяется она. Я попробую немного уменьшить квадрат, и добавить немного прозрачности к нему, или сделать его серее.
> 
> Способа иметь несколько иконок в приложении я не знаю.
> 
> Я использую свою иконку. :)

>  2. Обводка у (+ -)
> 
> Лучше убрать обводку у (+ -) сейчас в середине обводка дублитуется.
> 
> Когда я безуспешно пытался переписать программу на SwiftUI, то у меня нарисовался другой концепт для этих кнопок:
> https://github.com/SokoloffA/radiola/assets/854935/397e51de-48a6-4e7f-b042-e51b819920dd <https://github.com/SokoloffA/radiola/assets/854935/397e51de-48a6-4e7f-b042-e51b819920dd>
> Как вам?
> 
> Привычнее + – и меньше действий.
> 3. Ширина Sidebar
> 
> Sidebar (station/ tag...) дать возможность сжимать на усмотрение пользователей, сейчас слушком много пустого пространства остаёться.
> 
> Я не помню почему я задал такой большой минимум для ширины. Я сделаю поменьше. Это самое простое.
> 
> Было бы здорово если бы прилжение можно было бы сжать на своё усмотрение. Но есть проблема с панелью инструментов, её не сожмёшь. Я почти не использую интерфейс проги, но было бы хорошо отключить панель инструментов с зжать прогу до минимума, оставить только название станций. 

Пример: https://dropover.cloud/71e15e <https://dropover.cloud/71e15e>


> 4. Потребление памяти.
> 
> У меня при старте потребляет 10М, после начала воспроизведения 25М. Я думаю на современных машинах это норм, главное чтоб не текло.
> 
> С памятью, норм.
> 5. Верхние дуги слишком близко прилипают к иконке треугольника.
> 
> Иконка в меню баре: верхвние дуги слишком близко прилипают к иконке треугольника.
> Прикрепил пример как лучше.
> 
> Примера я не увидел ни в почте, ни на github. Но это не важно, я понял о чем ты. Я сделаю треугольник чуть меньше, возьму предыдущий кадр анимации.
> 
> Иконка мелочь, но если не лень то можно подправить.
> Пример: https://dropover.cloud/504df3
> Ничего я не пропустил?
> 
> 

Костя

**Comment by SokoloffA** [comment]
1 Основная иконка
-------------------
Займусь на выходных

2 Обводка у (+ -)
-----------------
**Готово.** Я поменял стиль кнопок, и добавил к ним подписи. Доп. кликов не надо. См. видео.

3 Ширина Sidebar
------------------
**Готово**
1. Уменьшил минимальную ширину 
2. Sidebar можно скрывать перетаскивая край, или через иконку в тулбаре. Но это и раньше можно было делать. Т.о. программу можно вернуть к старому виду. 
3. @kostazzz По поводу еще более минималистичного интерфейса, пожалуйста, заведи отдельный issue. Надо подумать и обсудить, в любом случае, в этот релиз это уже не лезет, сейчас только фикс багов.


4 Верхние дуги слишком близко прилипают к иконке треугольника.
-----------------------------------------------------------------------
**Готово.** Поменял иконки. 

---

@kostazzz 
>  Я использую свою иконку. :)

Поделись как.

---

https://github.com/SokoloffA/radiola/assets/854935/77dae4d7-b3dc-4348-9882-e55e2bb43aaf

**Comment by kostazzz** [comment]
Ого, как оперативно. :)

Если возможно иконку отключения звука не дублировать. 
https://dropover.cloud/dc0f7e


> 1 Основная иконка
> 
> Займусь на выходных
> 
> Я иконку взял из SF Symbols пака. Лично мне больше нравятся умеренные цвета или вообщё монохромные, время показывает, что они приживаются лучше. Приложил иконку, если надо мошешь изменить и использовать. :)


> 2 Обводка у (+ -)
> 
> Готово. Я поменял стиль кнопок, и добавил к ним подписи. Доп. кликов не надо. См. видео.
> 
> Норм, но UI стал шумнее, за то удобнее нажать, хотя нажимать надо только когда станции добовляешь, а после лишний элемент. Может без подписей, плюс и минус мне лично ближе, минималистичней и чище. Можно оставить из старых версий и сделать обводку 5% (-95%) прозрачность или вообще прозрачные. Раньше было норм, только рамка мешала или в swift нельзя так сделать? Наверняка можно иконки изменить выбрать -+.
> 3 Ширина Sidebar
> 
> Готово
> 
> Уменьшил минимальную ширину (клёво)
> Sidebar можно скрывать перетаскивая край, или через иконку в тулбаре. Но это и раньше можно было делать. Т.о. программу можно вернуть к старому виду. (да, а так и делал)
> @kostazzz <https://github.com/kostazzz> По поводу еще более минималистичного интерфейса, пожалуйста, заведи отдельный issue. Надо подумать и обсудить, в любом случае, в этот релиз это уже не лезет, сейчас только фикс багов.
3. Возможно это мог бы быть режим мини как в iTunes.

На гитхабе это сделать? Это вроде не проблема, а предложение или норм? Я не програмист, а граф. дизайнер :) не совсем понимаю как там вести темы.

**Comment by kolokolovg** [comment]
насчет утечки

первый скрин мой выше

вот сегодня после 2 дней
<img width="731" alt="image" src="https://github.com/SokoloffA/radiola/assets/21097728/7871140c-27fa-479a-a5f0-83490ccb3760">

возможно что то да подтекает.
я станции меняю регулярно раз в час-два

**Comment by kostazzz** [comment]
Я редко меняю станции, но после часа прослушивания не поднимается на прошлых версиях вроде буфер забивася, точно не помню, а сейчас всё стабильно. BigSur без прозрачности и уменьшено движение в настройках/ уневерсальный оступ, дисплэй.

**Comment by SokoloffA** [comment]
@kostazzz 

> На гитхабе это сделать? Это вроде не проблема, а предложение или норм? Я не програмист, а граф. дизайнер :) не совсем понимаю как там вести темы.

Да, прямо здесь, в issues для этого проекта, здесь и баги и пожелания заводят. Зайди на https://github.com/SokoloffA/radiola/issues и нажми на "New Issue".

Просто когда много пожеланий в одной теме, сложно отслеживать что сделал, а что нет. А потом не возможно найти обсуждение, заголовок "Blurred start/pause button inside the player" ну никак не отвечает ни новому дизайну, ни утечкам. Но если утечки это пока не баг а подозрение, то новый дизайн надо будет обсуждать, и лучше в отдельной теме.

**Comment by SokoloffA** [comment]
In release 7.0.0
