### ISSUE TITLE
Export/backup station list

### ISSUE THREAD

**Issue by Mateus109** [SokoloffA/radiola#33]
Please add the option to export (and import) the station lists.

In a sense the option is already there, if the end user knows where to look (~/Library/Application Support/com.github.SokoloffA.Radiola/bookmarks.opml), but it'd be nice to have a menu option for this process too.

**Comment by SokoloffA** [comment]
Yeah, I'll do it. No problem with exporting. But for import, I need to think about how to merge existing and new stations.

**Comment by SokoloffA** [comment]
I added this to the [beta version of Radiola 6.99.1](https://github.com/SokoloffA/radiola/releases/tag/v6.99.1).
If you are interested, you can test it by downloading [Radiola-6.99.1.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.1/Radiola-6.99.1.dmg)

**Comment by SokoloffA** [comment]
I have released the second beta, if you are interested you can download it [at the link](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by SokoloffA** [comment]
In release 7.0.0
