### ISSUE TITLE
suggestion copy name of song-artist

### ISSUE THREAD

**Issue by marcelo4768** [SokoloffA/radiola#34]
It would be useful to have a button as an option to copy the name of the song and the artist as a way to share or to search for information related to what is being heard

**Comment by SokoloffA** [comment]
Thank you for your interest in my program

How do you see it? I can do this in a number of ways:
1. Do CMD+C processing while the system menu is open.
2. Add a "Copy song title and artist" menu item to the system menu.
3. Add an action on the mouse button click on the icon.
4. Add a global shortcut for this.
5. Add a button to the history form.

**Comment by SokoloffA** [comment]
I added this to the [beta version of Radiola 6.99.1](https://github.com/SokoloffA/radiola/releases/tag/v6.99.1).
If you are interested, you can test it by downloading [Radiola-6.99.1.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.1/Radiola-6.99.1.dmg)

**Comment by SokoloffA** [comment]
I have released the second beta, if you are interested you can download it [at the link](https://github.com/SokoloffA/radiola/releases/download/v6.99.2/Radiola-6.99.2.dmg).

**Comment by SokoloffA** [comment]
In release 7.0.0
