### ISSUE TITLE
New main window layout suggestion

### ISSUE THREAD

**Issue by denilsonsa** [SokoloffA/radiola#36]
The current window layout has a few shortcomings:

* No button to create a group, making such feature hard to discover an somewhat annoying to use.
* The window widens automatically to fit the song title/author/info.
* There is a lot of empty space at the bottom, while the area for the song info has a large volume slider.

![Radiola-Before](https://github.com/SokoloffA/radiola/assets/121676/68b4e80a-aa12-4eae-a8f1-3418974244bd)

I propose this change (quick mockup made with Gimp):

![Radiola-After](https://github.com/SokoloffA/radiola/assets/121676/b56b300e-b656-4c41-b3e3-7587d43ef4a3)

As a bonus, the window doesn't need to automatically get wider to fit the song info. The info could wrap into multiple lines, or get cropped, or even scroll like a marquee (probably annoying).

**Comment by SokoloffA** [comment]
New beta of [Radiola-6.99.3.dmg](https://github.com/SokoloffA/radiola/releases/download/v6.99.3/Radiola-6.99.3.dmg) is ready.

>No button to create a group, making such feature hard to discover an somewhat annoying to use.

I've added such button.

>The window widens automatically to fit the song title/author/info.

I didn't plan for this behavior. Now: 
* the window doesn't change width, if the text doesn't fit, it is cropped with a ellipsis. 
* a tooltip with full text is shown when hovering the cursor.

>* There is a lot of empty space at the bottom, while the area for the song info has a large volume slider.

I thought about it, but I'm not sure.

**Comment by SokoloffA** [comment]
In release 7.0.0
