### ISSUE TITLE
"My stations" not saved at exit

### ISSUE THREAD

**Issue by mantered** [SokoloffA/radiola#37]
I deleted the default stations and added some new ones but they are lost after the app is closed.
After the app is restarted the default 3 stations are loaded. Is this a bug ?

(Latest radiola version on Sonoma 14.0)
![nodice](https://github.com/SokoloffA/radiola/assets/33768647/918c8fe4-dee6-49a8-8c90-9f1a5118b7aa)

**Comment by mantered** [comment]
it seems that I had no file in "BOOKMARK_PATH" so I created an empty bookmarks.opml but there was an error: "the radio station file was corrupted".
After I deleted the bookmarks.opml file and restarting the app, "Import station from a file" fixed the problem.
Now I have a new bookmarks.opml with the correct stations.

**Comment by SokoloffA** [comment]
It's definitely a bug. I was able to reproduce it and am fixing it right now.

**Comment by SokoloffA** [comment]
Fix of thes bug in the new release 7.0.1
