### ISSUE TITLE
Can't open the app anymore. 

### ISSUE THREAD

**Issue by Wiredframe** [SokoloffA/radiola#4]
Malware Warning... :/

**Comment by Wiredframe** [comment]
Seems to be an issue with the updater. 

`codesign -vv /Applications/Radiola.app 
/Applications/Radiola.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Applications/Radiola.app/Contents/Frameworks/Sparkle.framework`

**Comment by SokoloffA** [comment]
Oh, I'm sorry!
Please try the new version [Radiola-3.0.dmg.zip](https://github.com/SokoloffA/radiola/files/9758463/Radiola-3.0.dmg.zip), and give me a feedback.
_Unfortunately, github does not allow me to add a .dmg file, so I zipped it._

**Comment by Wiredframe** [comment]
Thanks mate! This one is working perfectly :) What did you change?

**Comment by SokoloffA** [comment]
I was thinking about brew, but I'm afraid my app doesn't meet the following condition from their [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff).

> **Niche (or self-submitted) stuff**
> The software in question must:
>* be known
>
> We frown on authors submitting their own work unless it is very popular.

**Comment by Wiredframe** [comment]
Didn't know about that, how unfortunate! People would love this app!

**Comment by SokoloffA** [comment]
You were wondering how I fixed it. I have a script for build release. Now the script looks like:
```
#!/bin/bash

APP_NAME=Radiola
VERSION=3.0
MAKE_DMG=true
#MAKE_DMG=false

BUILD_DIR=_build

#--------------------

set -Eeuo pipefail

BUNDLE_NAME="${APP_NAME}.app"
BUNDLE_PATH="./${BUNDLE_NAME}"
DMG_NAME="./${APP_NAME}-${VERSION}.dmg"

TAR="${APP_NAME}-${VERSION}.tar.gz"

if [[ ! -e ${TAR} ]]; then
    echo "${TAR} file not found" >&2
    exit 1
fi

rm -rf ${BUILD_DIR}
mkdir -p ${BUILD_DIR}/src
tar xf ${TAR} --directory=${BUILD_DIR}/src --strip 1.
xcodebuild -project ${BUILD_DIR}/src/${APP_NAME}.xcodeproj build
rm -rf ${BUNDLE_PATH}
cp -a ${BUILD_DIR}/src/build/Release/${APP_NAME}.app ${BUNDLE_PATH}
codesign -vv  ${BUNDLE_PATH}


if [[ MAKE_DMG ]]; then
    create-dmg \
        --volname ${APP_NAME} \
        --volicon ${BUNDLE_PATH}/Contents/Resources/AppIcon.icns \
        --window-size 500 300 \
        --icon-size 96 \
        --icon ${BUNDLE_NAME} 135 102 \
        --hide-extension ${BUNDLE_NAME} \
        --app-drop-link 365 102 \
        ${DMG_NAME} \
        ${BUNDLE_PATH}
fi
```
Previously, the line ```cp -a ${BUILD_DIR}/src/build/Release/${APP_NAME}.app ${BUNDLE_PATH}``` looked like ```cp -r ...```. [This post from stackoverflow](https://stackoverflow.com/questions/25969946/osx-10-9-5-code-signing-v2-signing-a-framework-with-bundle-format-is-ambiguou) helped me.
