### ISSUE TITLE
Feature Request: Change volume while adjusting slider

### ISSUE THREAD

**Issue by jprjr** [SokoloffA/radiola#44]
Hi there, just wanted to request a feature.

When I have Radiola open and I adjust the volume - the change doesn't kick in until I release the mouse. It would be great if it could change the volume as I slide it, so I get immediate feedback on the new volume.

**Comment by SokoloffA** [comment]
This functionality is already available in the development branch. 
And it will definitely be in the next release.

**Comment by SokoloffA** [comment]
Released in 8.0.0
