### ISSUE TITLE
Feature Request: Hide dock icon

### ISSUE THREAD

**Issue by nt294** [SokoloffA/radiola#45]
Firstly, thank you for this amazing piece of software! 

I was wondering if it would be possible to add a 'Hide dock icon' feature so it is just in the status bar? This is a feature in myTuner radio which I really liked, as I like to try and keep my dock as minimal as possible

**Comment by SokoloffA** [comment]
When you close the program window, the icon hides from the dock. At the same time, the icon in the status bar will remain. Playback will continue.
