### ISSUE TITLE
Feature Request: Keep status bar menu open after selecting station

### ISSUE THREAD

**Issue by nt294** [SokoloffA/radiola#46]
**Current behaviour:** When selecting a favourite station from the status bar, the menu closes automatically. This means that if you are browsing your stations (i.e. deciding which one you want to listen to) you need to reopen the menu each time and select the station. 

**Desired behaviour:** The station you selected will start playing, but the menu will remain open until clicked away from. This would allow you to quickly change between stations without having to reopen the menu, resulting in choosing a station much more user friendly.

**Comment by SokoloffA** [comment]
I am currently using the standard menu for the list of stations. His behavior is to hide after the click. Theoretically, your request is possible, but I will need to rewrite the entire menu. This will take some time. 

I'm thinking about replacing the menu with [popover](https://camo.githubusercontent.com/a11cbfcf2df6ae896ca8492eeeec6e08e1566f92dbc7cd2beb6da72de532fe94/68747470733a2f2f7261772e6769746875622e636f6d2f6d6178696d62696c616e2f4d61632d4f532d582d4170702d4d656e752d4261722d506f7075702f6d61737465722f73637265656e73686f74732f312e706e67). But I haven't decided yet whether it's necessary or not. And if necessary, how the popover should look like.
