### ISSUE TITLE
v8 takes RU as default language instead of EN

### ISSUE THREAD

**Issue by slackero** [SokoloffA/radiola#51]
After auto-updating from v7.0.2 to v8 Radiola was in Russian language only.
I could not find a setting to switch this to English again in the settings.

It helped to delete `Radiola.app/Contents/Resources/ru.lproj` to get English back after restarting the app.

My default system language is German DE, macOS 15.2, M1 Pro.
- my primary system language: DE
- alternative language 1: RU
- alternative language 2: EN

**Comment by SokoloffA** [comment]
If I understood you correctly, in the system settings (General -> Language & Region -> Preferred Languages) your language priorities are DE-RU-EN.

If so, then I don't see what the problem is. The program tries to use languages in this order, 
* DE - skip, no German translation.
* RU - Russian translation is available, use it.
* EN - we don't go to this point, because we found the translation in the previous point.

If you prefer English, then in the settings raise it higher than RU.
Or do you, for some reason, prefer English only in my program?

**Comment by SokoloffA** [comment]
In any case, you can set the language individually for the programs. See the last point in https://support.apple.com/en-az/guide/mac-help/mh26684/mac

**Comment by slackero** [comment]
Thanks @SokoloffA for your explanation.

The main problem is that I cannot switch to another (preferred) language.
My expectation is an option in the settings to overrule the language chosen automatically.

I need to check again if the automatism will respect the changed order of languages. And for sure, deliver a German translation.

**Comment by SokoloffA** [comment]
I will gladly accept German translations.

I use transifex.com to manage translations. Here is a [small instruction](https://github.com/SokoloffA/radiola/wiki/How-to-translate), maybe it will be useful for you.

**Comment by SokoloffA** [comment]
I received a request to add German. 
But I can't add you to the translators, the site says: 

>Profile not found
>It looks like the user you are looking for either does not exist or has a private profile.
>
>If you think that this profile should exist or be visible, please [let us know](https://app.transifex.com/contact/). Otherwise, you may [log in](https://app.transifex.com/signin/) to your account and work on something else.

https://app.transifex.com/user/profile/slackero/

**Comment by slackero** [comment]
Hello Alexander,

I translated Radiola into German.

You can always contact me directly by email or also by Telegram @slackero.

Greetings,
Oliver

--
Oliver Georgi ***@***.***>
Mobile +49–172-2842920 skype://slackero

**Comment by SokoloffA** [comment]
This is version with de_DE, it & ru translations [from CI](https://github.com/SokoloffA/radiola/actions/runs/12431813507)
[Radiola-8.0.0.dmg.zip](https://github.com/user-attachments/files/18211173/Radiola-8.0.0.dmg.zip)

**Comment by SokoloffA** [comment]
I need to [sort out the build scripts](https://github.com/SokoloffA/radiola/issues/54), after that I'll put out a new release.
