### ISSUE TITLE
option to keep history in front of other windows as "now playing"

### ISSUE THREAD

**Issue by acswift** [SokoloffA/radiola#52]
I would like to be able to keep the history window in front of all other applications' windows.

I listen to the radio, and I *always* want to know what song is playing and what were the last few songs.

For example: I'm programming in Terminal with the window filling the screen and it would be lovely to have the Radiola history window floating in front of the upper right corner.

If this were done, it might be nice to be able to be able to reduce the size down to a single line, the currently playing song.

I love your program — it's exactly what I've always wanted for listening to music at work.

**Comment by SokoloffA** [comment]
Do you really want to see history window all the time? The program has a tooltip on the icon that shows the name of the current song and artist. You can also set up a global keyboard shortcut to show the history window.

**Comment by acswift** [comment]
I know about the global shortcut; the problem is that if I have a full-screen Terminal window, it can only be active if it's in front of the Radiola window. I have to be *either* using Terminal *or* looking at the Radiola history.

I don't mind doing an action to show the window, but what I'm asking for is to have an *active* window behind the Radiola window. Perhaps I wasn't very clear.

Obviously it's not for everyone, but I program a lot and I have a big screen. I love music, and I'd love to have be able to glance at the history when a song comes on that I like.

I'm not demanding anything, I just thought it might be nice. The program is already awesome (I promoted it on X to my few followers and starred the repo).

**Comment by SokoloffA** [comment]
Since your wish is a rare thing, I added it to the main menu instead of the settings. Main menu -> Window -> Float on top
[You can check out the development version if you want.](https://github.com/user-attachments/files/18221883/Radiola-8.0.0.dmg.zip)

P.S. Please don't get confused, I didn't change the version number of the program.

**Comment by acswift** [comment]
It's great, I can't believe you implemented it, let alone so quickly!

I have a couple of suggestions to make things clearer for other users. This is just feedback, not a request.
- consider changing "history" to "song titles" or "track titles" (for me, the now playing part is much more interesting than the history aspect, and it took me a few weeks to realize that that is what History is.
- it's nice to be able to shrink the History window now, but you might want to make the smallest size big enough to show only the "now playing" title — I don't see the utility of shrinking it down to the title bar
- the floating option applies to both the main window and the history window, separately. It might be more clear if it was just History, and labeled "Keep History in Front" (it took me a few minutes to figure out why the history wasn't floating — I had floated the main window

Anyway, a big thanks, it's a great app and I'll continue to recommend it to anyone who will listen.

**Comment by acswift** [comment]
Also it might be nice to move the checkbox "show only your favorite songs" to a preference instead of being permanently visible in the history window — it takes up precious screen space and will presumably only be used once.

Thanks again!

**Comment by SokoloffA** [comment]
Unfortunately no, this checkbox is an operational setting. Let's try to solve the problem in a different way. If the window size is reduced below a certain height (say 250 px), this panel will be hide. 

What do you think?

**Comment by acswift** [comment]
That's a perfect solution.

**Comment by SokoloffA** [comment]
I hide the bottom panel if the height of the history window is less than 250.
[Radiola-8.0.0.dmg.zip](https://github.com/user-attachments/files/18269209/Radiola-8.0.0.dmg.zip)

**Comment by SokoloffA** [comment]
I need to [sort out the build scripts](https://github.com/SokoloffA/radiola/issues/54), after that I'll put out a new release.

**Comment by SokoloffA** [comment]
Published in Release 8.1.0

**Comment by acswift** [comment]
I installed it and it's great. Thanks so much!
