### ISSUE TITLE
Automate release process to ensure semver

### ISSUE THREAD

**Issue by toobuntu** [SokoloffA/radiola#54]
Congratulations, Radiola now meets the notability threshold for inclusion in Homebrew (> 75 stars)!

As self-submitted software is frowned upon, I would like to submit the cask there on your behalf. There is something that has to be resolved first: the history of Radiola's GitHub release tags having `MAJOR.MINOR.PATCH` or `MAJOR.MINOR` format. Homebrew devs want to see the upstream handled consistently so their automation can properly update the cask definition in CI.

---

The issue: In the past (5.2.0 and even 6.0.0), there have been instances where the GitHub release is tagged v6.0 but the Radiola version is 6.0.0 and sometimes the GitHub release is tagged v8.0.0 and the Radiola version is 8.0.0. This causes a problem for cask definition updates using Homebrew's automated tool--`brew bump` (which uses `brew livecheck` and `brew bump-cask-pr` under the hood), as it is not designed to handle switching between `#{version}` and `#{version.major_minor}` in the [cask definition file](https://github.com/SokoloffA/homebrew-radiola/blob/main/Casks/radiola.rb#L5-L9 "https://github.com/SokoloffA/homebrew-radiola/blob/main/Casks/radiola.rb#L5-L9") and the devs will not change their code to handle it.

This request is to consider an enforcement mechanism so it won't be possible to forget and wind up with inconsistencies anymore. If [semver](https://semver.org "https://semver.org") is strictly enforced, for example, then both tag and version will include `MAJOR.MINOR.PATCH` all the time.

There are several possibilities for implementing this. One could write a custom script, use [Commitizen](https://github.com/commitizen-tools/commitizen/blob/master/docs/commands/bump.md "https://github.com/commitizen-tools/commitizen/blob/master/docs/commands/bump.md"), or use any of the GitHub Actions which try to help (listed in no particular order): 
https://github.com/semantic-release/github with https://github.com/softprops/action-gh-release
https://github.com/remorses/bump-version
https://github.com/MeilCli/bump-release-action
https://github.com/anothrNick/github-tag-action#bumping
https://github.com/googleapis/release-please-action
https://github.com/PaulHatch/semantic-version
https://github.com/mahinops/github-manual-release

(In evaluating those options, you might want to look at the number of stars and most recent commit dates.)

You might also consider the usefulness of maintaining a `VERSION` file or reading `CURRENT_PROJECT_VERSION` in [`Radiola.xcodeproj/project.pbxproj`](https://github.com/SokoloffA/radiola/blob/main/Radiola.xcodeproj/project.pbxproj#L778) in any bespoke script.

With this issue resolved, I think it would be possible to move Radiola to the official [Homebrew/cask](https://github.com/Homebrew/homebrew-cask "https://github.com/Homebrew/homebrew-cask") repository.

**Comment by SokoloffA** [comment]
> Congratulations, Radiola now meets the notability threshold for inclusion in Homebrew (> 75 stars)!

WOW! I didn't even notice!

> There is something that has to be resolved first: the history of Radiola's GitHub release tags having MAJOR.MINOR.PATCH or MAJOR.MINOR format.

MAJOR.MINOR was a mistake on my part, now I only use the MAJOR.MINOR.PATCH format.

> The issue: In the past (5.2.0 and even 6.0.0), there have been instances where the GitHub release is tagged v6.0 but the Radiola version is 6.0.0 and sometimes the GitHub release is tagged v8.0.0 and the Radiola version is 8.0.0. 

As I wrote 5.2.0 and 6.0.0 is my mistake. Now I always use the format with three numbers.
I don't see what is the problem with 8.0.0?  Title is *Release 8.0.0*, tag is *v8.0.0*, DMG file *Radiola-8.0.0.dmg*. Or the tag can't contain a prefix?

> There are several possibilities for implementing this.

Thanks for the advice, I will look at the options and apply one of them, I will post here afterwards.

**Again, thank you very much for your interest in the project!**

**Comment by toobuntu** [comment]
No worries. Mistakes happen. Automation can help reduce its likelihood.

Perhaps I could have been more clear. There is _no_ problem with 8.0.0. It's exactly as it should be. The v prefix is totally fine, and also very common.

Unfortunately, I overlooked that Homebrew will not take new packages which are not notarized and require `--no-quarantine`. So it seems Radiola will have to remain in your private tap after all.

**Comment by SokoloffA** [comment]
> Unfortunately, I overlooked that Homebrew will not take new packages which are not notarized and require --no-quarantine. So it seems Radiola will have to remain in your private tap after all.

What do you mean by "not notarized"?
I have an Apple developer account.
I sign the app using the `codesign --force --deep --verify --sign  "${CERT_IDENTITY}" "${BUNDLE_PATH}"`, `codesign --all-architectures -v --strict --deep --verbose=1 "${BUNDLE_PATH}"` and `spctl --assess --type execute "${BUNDLE_PATH}"` commands in the script "https://github.com/SokoloffA/radiola/blob/main/.github/workflows/makedmg.sh".

I sign manually rather than during CI workflow, but all artifacts are signed.
```
% codesign --all-architectures -v --strict --deep --verbose=1 /Applications/Radiola.app && echo "codesign OK"
codesign OK
% spctl --assess --type execute /Applications/Radiola.app && echo "spctl OK"
spctl OK
```
Do I have to do anything else?

**Comment by toobuntu** [comment]
I am glad to stand corrected. I got confused by the --no-quarantine requirement. But your cask does pass the new cask audit[1]. So it seems like it should be acceptable in Homebrew itself, after all.

[1] `brew audit --new --cask sokoloffa/radiola/radiola`

**Comment by toobuntu** [comment]
When I `brew uninstall radiola` and `brew install radiola` without `--no-quarantine` I get the following:
![Screenshot 2024-12-24 at 10 06 09 AM](https://github.com/user-attachments/assets/3f6cb1fb-0760-4976-8bb1-5909bb1b6d10)

So there is still an issue here. Signing and [notarizing](https://forum.c-command.com/t/do-i-have-to-notarize-my-dmg-and-my-app-when-distributing/14604 "https://forum.c-command.com/t/do-i-have-to-notarize-my-dmg-and-my-app-when-distributing/14604") are different.

https://developer.apple.com/documentation/security/notarizing-macos-software-before-distribution

**Comment by SokoloffA** [comment]
Thanks for the clarification. 

Yesterday I failed to get the program notarized. I got an error _"The executable does not have the hardened runtime enabled."_ even though “hardened runtime” is enabled in the project.
![image](https://github.com/user-attachments/assets/c0880858-946d-4e66-abd2-9efeb37c7261)

It's possible that my workflow is wrong. I'm wary of uploading my certificates to github, so:
1. In CI, I build the project without signing `codebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO`.
2. Then I sign the project and package it in dmg  [makedmg.sh](https://github.com/SokoloffA/radiola/blob/main/.github/workflows/makedmg.sh).

Maybe the first point step disables hardened. I'll be battling this over New Year's break.

If you know of projects that have successfully solved similar problems, I'd love to see how they did it.

**Comment by toobuntu** [comment]
> Maybe the first point step disables hardened.

it seems so.

Are you setting `--options=runtime` in `OTHER_CODE_SIGN_FLAGS` as described [here](https://developer.apple.com/documentation/security/resolving-common-notarization-issues#Enable-the-hardened-runtime "https://developer.apple.com/documentation/security/resolving-common-notarization-issues#Enable-the-hardened-runtime")?

While not the same as your workflow, Rectangle is [resigning](https://github.com/rxhanson/Rectangle/blob/main/.github/workflows/build.yml#L36-L37 "https://github.com/rxhanson/Rectangle/blob/main/.github/workflows/build.yml#L36-L37") with `--force`.

I understand that you don’t want to put your certificate in GitHub as a secret. Are you using an [app-specific password](https://support.apple.com/en-us/102654 "https://support.apple.com/en-us/102654")? Maybe that would be less scary to store as a GitHub secret. At any rate, I guess you can build, sign, notarize and staple locally (outside of CI) and upload the asset to the release manually every time. Alternatively, you could investigate whether a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners "https://docs.github.com/en/actions/hosting-your-own-runners") would suit your needs.

**Comment by toobuntu** [comment]
Most open source projects I've looked at are using GitHub Actions CI.

Examples:
https://github.com/CodeEditApp/CodeEdit/blob/f580ef5ff3de3603c3a3762f45ea9adbf1a14a85/.github/workflows/pre-release.yml#L69

https://github.com/zed-industries/zed/blob/main/script/bundle-mac#L317

NetNewsWire is encrypting their secrets and using them from the macOS Keychain: https://github.com/Ranchero-Software/NetNewsWire/blob/main/buildscripts/ci-build.sh

ProtonVPN uses obfuscated constants in a separate repository: https://github.com/ProtonVPN/ios-mac-app#obfuscated-constants

MacDown has a build script in Python, but without code signing or notarization: https://github.com/MacDownApp/macdown/blob/master/Tools/build_for_release.py

**Comment by toobuntu** [comment]
> 2. Then I sign the project and package it in dmg [makedmg.sh](https://github.com/SokoloffA/radiola/blob/main/.github/workflows/makedmg.sh).

Among other things, `--deep` is considered deprecated for signing as of macOS 13.0, per the man page, and it seems to be missing `--options=runtime` to apply the hardened runtime. As I understand it, one is now supposed to recursively sign all of the helpers, tools, libraries, frameworks, and other components that the app relies on, and that are bundled with the app, from the inside out. Here's just two examples I found (I cannot vouch for them): [SignApp.sh](https://github.com/miyako/4d-class-compiler/blob/main/Resources/bin/macOS/SignApp.sh "https://github.com/miyako/4d-class-compiler/blob/main/Resources/bin/macOS/SignApp.sh") (10 months old) and [codesigndeveloperid.pl](https://gist.github.com/jerrykrinock/9d2359234797da97a94d "https://gist.github.com/jerrykrinock/9d2359234797da97a94d") (6 years old). Are you using [entitlements](https://developer.apple.com/documentation/bundleresources/diagnosing-issues-with-entitlements#Check-the-Entitlements-When-Submitting-Your-App "https://developer.apple.com/documentation/bundleresources/diagnosing-issues-with-entitlements#Check-the-Entitlements-When-Submitting-Your-App")?

> If you know of projects that have successfully solved similar problems, I'd love to see how they did it.

See [here](https://gregoryszorc.com/docs/apple-codesign/stable/apple_codesign_github_actions.html "https://gregoryszorc.com/docs/apple-codesign/stable/apple_codesign_github_actions.html") for some ideas, but the author [states](https://gregoryszorc.com/docs/apple-codesign/main/apple_codesign_quirks.html#cannot-sign-file-contents-of-dmgs "https://gregoryszorc.com/docs/apple-codesign/main/apple_codesign_quirks.html#cannot-sign-file-contents-of-dmgs") explicitly "if you have access to macOS you should probably just use Apple’s official signing tooling".

Perhaps this can be useful: https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/

At least at one version of Xcode, codesign would fail if any component of a target package had any extended attributes, so people would `/usr/bin/xattr -r -c <path>` to clear them recursively prior to signing.

**Comment by SokoloffA** [comment]
I publish a new [release 8.1.0](https://github.com/SokoloffA/radiola/releases/tag/v8.1.0). I managed to notirize the application, not the first time, but succeeded (I hope). 

```
spctl -a -vvv -t install Radiola.app
Radiola.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Alex Sokolov (635H9TYSZJ)
```

**Comment by toobuntu** [comment]
I tried it and it is notarized. I also see that you check the release tag now. So I'm comfortable submitting this to Homebrew. It looks correct, since your betas also follow the format v6.99.3, etc. If those betas are _not_ labeled as the _Latest_ release in GitHub, then we can simplify the livecheck stanza to just use `github_latest`.

**Comment by SokoloffA** [comment]
I don't mark beta versions as github_latest, and I mark them as pre-release. 

Apparently I can close this issue.
