### ISSUE TITLE
Keyboard control key "play/pause" play twice sources

### ISSUE THREAD

**Issue by ingozoell** [SokoloffA/radiola#8]
Hi,

when Radiola plays and I hit play/pause key on my keybord Radiola play twice sources at the same time:
Appers by apps and web-browser services: iTunes/Music, YouTube/YouTubeMusic

Is it possible to disable this key function for control Radiola or another workaround to avoid playing two sources at the time?

Thanks and regards, Ingo

<img width="1278" alt="mac-keyboard-play-pause" src="https://github.com/SokoloffA/radiola/assets/2229940/8737428e-c4d1-4209-90f2-f6abb2ff9934">

**Comment by SokoloffA** [comment]
I could have sworn that the program has a checkbox in the settings for this. But I was surprised to see that he was not there. Many months ago I started to do it, but something prevented me. 

Of course I will add a checkbox to enable/disable the program's response to multimedia keys.

**Comment by ingozoell** [comment]
Great
