### ISSUE TITLE
Feature request: click to mute

### ISSUE THREAD

**Issue by juanfcocontreras** [SokoloffA/radiola#9]
I think it should very useful be able to mute by clicking the voiceless speaker icon in the volume bar. Another click on the same icon should restore the previous volume. Sometimes you want to mute a moment the music, without having to stop it.

Another more difficult to implememnt feature request should be able to turn up and down the volume by scrolling in the icon of the menu bar.

Thanks for your great and useful app!

**Comment by SokoloffA** [comment]
I did everything you asked. I'll be putting out a release shortly.

**Comment by juanfcocontreras** [comment]
Thank you so much! Just two minor things:

- could you add a mute button also to the menu bar window (not only to the main window)?
- can scroll direction respect system settings? In my system, when I scroll up, the volumen goes down, and the opposite.

Thank you so much again!

**Comment by SokoloffA** [comment]
> could you add a mute button also to the menu bar window (not only to the main window)?

Yes, I can do it, just a little later. 
I also thought that I could add a mute by clicking left/middle/right mouse button on the icon. Of course it will be configurable. I was stopped by the need to draw a program icon for the loaded state, this require some time.

>can scroll direction respect system settings? In my system, when I scroll up, the volumen goes down, and the opposite.

It looks like the "Natural scrolling" mode is turned on for you. 
![](https://www.askdavetaylor.com/wp-content/uploads/2023/03/mac-macos-trackpad-mouse-settings-4.png)

In this case, the program illogically changes the volume. I'll fix it.

**Comment by SokoloffA** [comment]
> can scroll direction respect system settings? In my system, when I scroll up, the volumen goes down, and the opposite.

Done in 5.1.1

**Comment by SokoloffA** [comment]
@juanfcocontreras 
By the way, right now you can configure play/pause toggling by click mouse buttons on the icon in the status bar.
![settings](https://github.com/SokoloffA/radiola/assets/854935/50203e20-1351-43bf-b3a7-c1f823dec6af)
It's not muting, but maybe it will usable for you.

**Comment by juanfcocontreras** [comment]
> It looks like the "Natural scrolling" mode is turned on for you. 
> 
> In this case, the program illogically changes the volume. I'll fix it.

Exactly, thank you so much! Now it's working great!

> It's not muting, but maybe it will usable for you.

Sometimes some radios take a long time to connect, so I prefer to mute for a short pause.
